version: '3.7'

networks:
  land_network:
    name: land_network

services:

# CouchDB
  couchdb0:
    image: couchdb:3.3
    container_name: couchdb0
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-adminpw}
    ports:
      - "127.0.0.1:5984:5984"
    networks:
      - land_network

  couchdb1:
    image: couchdb:3.3
    container_name: couchdb1
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-adminpw}
    ports:
      - "127.0.0.1:7984:5984"
    networks:
      - land_network


# -------------------------
# Peer Org1
# -------------------------

  peer0.org1.landregistry.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.org1.landregistry.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto/peerOrganizations/org1.landregistry.com/peers/peer0.org1.landregistry.com/msp
      - CORE_PEER_ID=peer0.org1.landregistry.com
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.landregistry.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.landregistry.com:7051
      - CORE_PEER_ADDRESS=peer0.org1.landregistry.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.landregistry.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=land_network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_USER:-admin}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PASSWORD:-adminpw}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/crypto/peerOrganizations/org1.landregistry.com/peers/peer0.org1.landregistry.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/crypto/peerOrganizations/org1.landregistry.com/peers/peer0.org1.landregistry.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto/peerOrganizations/org1.landregistry.com/peers/peer0.org1.landregistry.com/tls/ca.crt

    volumes:
      - ./crypto-config:/etc/hyperledger/fabric/crypto
      - /var/run/docker.sock:/host/var/run/docker.sock

    ports:
      - "7051:7051"

    depends_on:
      - couchdb0

    networks:
      - land_network

# -------------------------
# Peer Org2
# -------------------------

  peer0.org2.landregistry.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.org2.landregistry.com

    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto/peerOrganizations/org2.landregistry.com/peers/peer0.org2.landregistry.com/msp
      - CORE_PEER_ID=peer0.org2.landregistry.com
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.landregistry.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.landregistry.com:9051
      - CORE_PEER_ADDRESS=peer0.org2.landregistry.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.landregistry.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=land_network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_USER:-admin}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PASSWORD:-adminpw}

    volumes:
      - ./crypto-config:/etc/hyperledger/fabric/crypto
      - /var/run/docker.sock:/host/var/run/docker.sock

    ports:
      - "9051:9051"

    depends_on:
      - couchdb1

    networks:
      - land_network


# -------------------------
# Orderer 0
# -------------------------

  orderer0.landregistry.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer0.landregistry.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer0.landregistry.com/msp
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=genesisFile
      - ORDERER_GENERAL_BOOTSTRAPFILE=/etc/hyperledger/fabric/genesisblock
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer0.landregistry.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer0.landregistry.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer0.landregistry.com/tls/ca.crt]
    volumes:
      - ./genesis.block:/etc/hyperledger/fabric/genesisblock
      - ./crypto-config:/etc/hyperledger/fabric/crypto
    ports:
      - "7050:7050"
    networks:
      - land_network


# -------------------------
# Orderer 1
# -------------------------

  orderer1.landregistry.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer1.landregistry.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer1.landregistry.com/msp
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/fabric/genesisblock

      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer1.landregistry.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer1.landregistry.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer1.landregistry.com/tls/ca.crt]
    volumes:
      - ./genesis.block:/etc/hyperledger/fabric/genesisblock
      - ./crypto-config:/etc/hyperledger/fabric/crypto
    ports:
      - "8050:8050"
    networks:
      - land_network


# -------------------------
# Orderer 2
# -------------------------

  orderer2.landregistry.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer2.landregistry.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer2.landregistry.com/msp
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/fabric/genesisblock

      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer2.landregistry.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer2.landregistry.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/crypto/ordererOrganizations/landregistry.com/orderers/orderer2.landregistry.com/tls/ca.crt]
    volumes:
      - ./genesis.block:/etc/hyperledger/fabric/genesisblock
      - ./crypto-config:/etc/hyperledger/fabric/crypto
    ports:
      - "9050:9050"
    networks:
      - land_network